#!/bin/bash
#does git add and commit "
git status
echo
echo
echo "Moving forward...."
sleep 3
read -p "what do you want to git (eg., file1.c file2.py) " files
git add $files

read -p "Enter commit mesage: " message
git commit -m "$message"

git push
